import { useReducer } from "react";
import { chatReducer } from "@vagus/ui-chat";
import type { ChatItem, HistoryMessage } from "@vagus/ui-chat";
import type { DomainEvent } from "@vagus/ui-shared";

/**
 * Per-session UI state — the multi-session core.
 *
 * Every live session keeps its own slot (`items`, `busy`, queued rail, …)
 * so background agents keep streaming into their slot while the user is
 * looking at another chat. Switching sessions is just `activate()`: the
 * slot's content is already there, nothing is cleared or reloaded.
 *
 * The reducer is pure — all side effects (scrolling, RPC refreshes) live in
 * the event subscription (useVagusClient) — and events carry an explicit
 * `id` generated by the caller, so this module stays testable.
 */

export interface QueuedMessage {
  id: number;
  text: string;
}

export interface SessionInfo {
  model?: string;
  activeProvider?: string;
  thinkingLevel?: string;
  tokens: { input: number; output: number; cacheRead: number; cacheWrite: number; total: number };
  /** Current context occupancy (post-compaction this drops). */
  contextUsage?: { tokens: number | null; contextWindow: number; percent: number | null };
  cost: number;
  /** Cache hit rate of the latest assistant message (pi footer semantics). */
  latestCacheHitRate?: number;
  cacheStats?: { missedTokens: number; missedCost: number; missCount: number };
}

export interface SessionSlot {
  /** Chat timeline (chatReducer state). */
  items: ChatItem[];
  /** True while this session's agent is working (turn start → end). */
  busy: boolean;
  /** Epoch ms when the current turn started (work-duration display). */
  turnStart?: number;
  /** User messages queued for steering (pi's authoritative queue). */
  queued: QueuedMessage[];
  thinkingLevel?: string;
  info?: SessionInfo;
  /** True when older messages exist (lazy-load pagination). */
  historyHasMore: boolean;
  /** Total visible messages in the session history. */
  historyTotal: number;
  /** View-space index of the oldest loaded message (next page reads before it). */
  historyStartIndex: number;
}

/** Slot key for the "no active session" welcome state (new-chat hint). */
export const WELCOME_SLOT = "__welcome__";

export function emptySlot(): SessionSlot {
  return { items: [], busy: false, queued: [], thinkingLevel: undefined, info: undefined, historyHasMore: false, historyTotal: 0, historyStartIndex: 0 };
}

export interface SessionStoreState {
  activeId: string | undefined;
  slots: Record<string, SessionSlot>;
}

export type SessionStoreAction =
  | { type: "activate"; sessionId: string | undefined }
  | { type: "applyEvent"; sessionId: string; id: number; event: DomainEvent }
  | { type: "loadHistory"; sessionId: string; id: number; messages: HistoryMessage[]; hasMore?: boolean; total?: number; startIndex?: number }
  | { type: "prependHistory"; sessionId: string; id: number; messages: HistoryMessage[]; hasMore: boolean; total: number; startIndex: number }
  | { type: "clearActive" }
  | { type: "localSystem"; id: number; text: string }
  | { type: "removeMessage"; id: number }
  | { type: "setInfo"; sessionId: string; info: SessionInfo | undefined; thinkingLevel?: string }
  | { type: "toggleCollapse"; id: number }
  | { type: "forceIdle" }
  | { type: "moveWelcome"; sessionId: string }
  | { type: "userMessage"; sessionId: string; id: number; text: string; skillTag?: string; images?: Array<{ dataUrl: string; mimeType: string }> };

function slotId(state: SessionStoreState): string {
  return state.activeId ?? WELCOME_SLOT;
}

function updateSlot(state: SessionStoreState, id: string, update: (slot: SessionSlot) => SessionSlot): SessionStoreState {
  const prev = state.slots[id] ?? emptySlot();
  const next = update(prev);
  if (next === prev) return state;
  return { ...state, slots: { ...state.slots, [id]: next } };
}

/** Hook: the multi-session store. Derived views read the active slot. */export function sessionStoreReducer(state: SessionStoreState, action: SessionStoreAction): SessionStoreState {
  switch (action.type) {
    case "activate":
      return { ...state, activeId: action.sessionId };
    case "clearActive":
      return { ...state, activeId: undefined };
    case "loadHistory":
      return updateSlot(state, action.sessionId, (slot) => ({
        ...emptySlot(),
        items: chatReducer([], { type: "historyLoaded", id: action.id, messages: action.messages }),
        info: slot.info,
        thinkingLevel: slot.thinkingLevel,
        historyHasMore: action.hasMore ?? false,
        historyTotal: action.total ?? action.messages.length,
        historyStartIndex: action.startIndex ?? Math.max(0, (action.total ?? action.messages.length) - action.messages.length),
      }));
    case "prependHistory":
      return updateSlot(state, action.sessionId, (slot) => ({
        ...slot,
        items: chatReducer(slot.items, { type: "prependHistory", id: action.id, messages: action.messages }),
        historyHasMore: action.hasMore,
        historyTotal: action.total,
        historyStartIndex: action.startIndex,
      }));
    case "localSystem":
      return updateSlot(state, slotId(state), (slot) => ({
        ...slot,
        items: chatReducer(slot.items, { type: "system", id: action.id, text: action.text }),
      }));
    case "removeMessage":
      return updateSlot(state, slotId(state), (slot) => ({
        ...slot,
        items: chatReducer(slot.items, { type: "removeMessage", id: action.id }),
      }));
    case "userMessage":
      return updateSlot(state, action.sessionId, (slot) => ({
        ...slot,
        items: chatReducer(slot.items, {
          type: "userMessage", id: action.id, text: action.text,
          ...(action.skillTag ? { skillTag: action.skillTag } : {}),
          ...(action.images && action.images.length > 0 ? { images: action.images } : {}),
        }),
      }));
    case "setInfo":
      return updateSlot(state, action.sessionId, (slot) => ({
        ...slot,
        info: action.info,
        thinkingLevel: action.thinkingLevel ?? slot.thinkingLevel,
      }));
    case "toggleCollapse":
      return updateSlot(state, slotId(state), (slot) => ({
        ...slot,
        items: chatReducer(slot.items, { type: "toggleCollapse", id: action.id }),
      }));
    case "forceIdle":
      // Prompt/send error fallback — make sure the spinner isn't stuck.
      return updateSlot(state, slotId(state), (slot) =>
        slot.busy || slot.turnStart !== undefined ? { ...slot, busy: false, turnStart: undefined } : slot,
      );
    case "moveWelcome": {
      // Carry the welcome hint (new-session system message) into the fresh
      // session's slot when the first message creates it, then drop the slot.
      const welcome = state.slots[WELCOME_SLOT];
      if (!welcome || welcome.items.length === 0) return state;
      const target = state.slots[action.sessionId] ?? emptySlot();
      const slots = { ...state.slots };
      slots[action.sessionId] = {
        ...target,
        items: [...target.items, ...welcome.items],
        thinkingLevel: target.thinkingLevel ?? welcome.thinkingLevel,
      };
      delete slots[WELCOME_SLOT];
      return { ...state, slots };
    }
    case "applyEvent": {
      const { sessionId, id, event } = action;
      return updateSlot(state, sessionId, (slot) => applyEventToSlot(slot, id, event));
    }
  }
}

/** Pure: folds one domain event into a session slot's state. */
function applyEventToSlot(slot: SessionSlot, id: number, event: DomainEvent): SessionSlot {
  switch (event.type) {
    case "session.turn":
      if (event.kind === "start") {
        return { ...slot, busy: true, turnStart: Date.now() };
      }
      // Turn fully done — stamp the work block with its total duration.
      if (slot.turnStart !== undefined) {
        const items = chatReducer(slot.items, {
          type: "turnEnd",
          startedAt: slot.turnStart,
          endedAt: Date.now(),
        });
        return { ...slot, busy: false, turnStart: undefined, items };
      }
      return { ...slot, busy: false, turnStart: undefined };
    case "session.message":
      if (event.kind === "text_delta") {
        return { ...slot, items: chatReducer(slot.items, { type: "assistantDelta", id, text: event.text }) };
      }
      if (event.kind === "text_done") {
        // The reply is complete — collapse this turn's work content.
        return { ...slot, items: chatReducer(slot.items, { type: "collapseAll" }) };
      }
      if (event.kind === "user_queued") {
        // pi injected a queued message into the loop — move it into the
        // timeline. Queue removal is driven by queue_update (authoritative).
        const images = (event as { images?: Array<{ dataUrl: string; mimeType: string }> }).images;
        return { ...slot, items: chatReducer(slot.items, { type: "userMessage", id, text: event.text, ...(images && images.length > 0 ? { images } : {}) }) };
      }
      if (event.kind === "error") {
        // Model/loop failure surfaced by pi — show it inline instead of a
        // silent turn end.
        return { ...slot, items: chatReducer(slot.items, { type: "system", id, text: `⚠ ${event.text}` }) };
      }
      return slot;
    case "session.thinking":
      if (event.kind === "delta") {
        return { ...slot, items: chatReducer(slot.items, { type: "thinkingDelta", id, text: event.text }) };
      }
      // thinking_done — finalize the current thinking card.
      return { ...slot, items: chatReducer(slot.items, { type: "thinkingDone", id }) };
    case "session.tool_call":
      return {
        ...slot,
        items: chatReducer(slot.items, {
          type: "toolCallStarted",
          id,
          toolCallId: event.toolCallId,
          name: event.name,
          args: event.args,
        }),
      };
    case "session.tool_result":
      return {
        ...slot,
        items: chatReducer(slot.items, {
          type: "toolCallFinished",
          toolCallId: event.toolCallId,
          result: event.result,
          isError: event.isError,
          ...(event.diff !== undefined ? { diff: event.diff } : {}),
          ...(event.patch !== undefined ? { patch: event.patch } : {}),
        }),
      };
    case "session.queue_update": {
      // Authoritative steering-queue state from pi — rebuild the queued rail.
      const steering = (event as { steering?: string[] }).steering ?? [];
      const idByText = new Map<string, number>();
      let maxId = 0;
      for (const q of slot.queued) {
        idByText.set(q.text, q.id);
        if (q.id > maxId) maxId = q.id;
      }
      let next = maxId + 1;
      return { ...slot, queued: steering.map((text) => ({ id: idByText.get(text) ?? next++, text })) };
    }
    case "session.subagent": {
      // Subagent lifecycle (from @tintinweb/pi-subagents via the bridge).
      // Render as a system note in the timeline so the user sees what child
      // agents are doing and what they returned.
      const kind = event.kind;
      const type = event.agentType ? `[${event.agentType}] ` : "";
      let text = "";
      if (kind === "created" || kind === "started") {
        text = `🧩 子代理 ${type}开始：${event.description ?? event.agentId ?? ""}`;
      } else if (kind === "completed") {
        text = `✅ 子代理 ${type}完成：${(event.result ?? "").slice(0, 500)}`;
      } else if (kind === "failed") {
        text = `❌ 子代理 ${type}失败：${event.error ?? event.result ?? ""}`;
      } else if (kind === "steered") {
        text = `📮 子代理 ${type}收到指示：${event.description ?? ""}`;
      } else if (kind === "compacted") {
        text = `🧹 子代理 ${type}已压缩上下文`;
      } else {
        return slot;
      }
      return { ...slot, items: chatReducer(slot.items, { type: "system", id, text }) };
    }
    default:
      return slot;
  }
}

/** Hook: the multi-session store. Derived views read the active slot. */
export function useSessionStore(): {
  state: SessionStoreState;
  dispatch: React.Dispatch<SessionStoreAction>;
  active: SessionSlot;
} {
  const [state, dispatch] = useReducer(sessionStoreReducer, { activeId: undefined, slots: {} });
  const active = state.slots[state.activeId ?? WELCOME_SLOT] ?? emptySlot();
  return { state, dispatch, active };
}
